# Generated by Django 6.0 on 2025-12-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='register_number',
            field=models.CharField(default='TEMP001', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(),
        ),
    ]
